channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- python>=3.11,<3.13
- pip
- numpy =1.26.4
- ase =3.26.0
- pymatgen =2025.6.14
- pyiron_workflow =0.15.2
- pyiron_lammps =0.4.6
- pandas =2.3.1
- lammps =2024.08.29
- pysqa =0.3.0
- pip:
  - pyiron-workflow-atomistics==0.0.3
  - pyiron-snippets==0.2.0
  - -e .[dev]
