channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- python=3.12
- pip
- numpy =1.26.4
- ase =3.26.0
- pymatgen =2025.6.14
- pyiron_workflow =0.15.2
- pyiron_lammps =0.4.6
- pysqa =0.3.0
- pip:
  - pyiron_workflow_atomistics=0.0.1
  - pyiron_snippets=0.1.0
  - -e .[dev]
